name: github-actions for java project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile_code:
    name: code compile job
    runs-on: self-hosted
    steps:
    - name: checkout code repo
      uses: actions/checkout@v4
    - name: set up jdk installation
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: build with maven
      run: mvn compile 
