name: github-actions for java project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile-code:
    name: code compile job
    runs-on: self-hosted
    steps:
    - name: checkout code repo
      uses: actions/checkout@v4
    - name: set up jdk installation
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: build with maven
      run: mvn compile 
  
  security-check:
    runs-on: self-hosted
    needs: compile-code
    steps:
    - name: checkout code repo
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: trivy dependency scan
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        format: 'table'
        scan-type: 'fs'
        scan-ref: '.'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
    - name: git leaks scan for detecting hardcoded secrets
      uses: gitleaks/gitleaks-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-testing:
    runs-on: self-hosted
    needs: security-check
    steps:
    - name: checkout code repo
      uses: actions/checkout@v4
    - name: setup java installation
      uses: actions/setup-java@v4
      with:
        version: '21'
        distribution: 'temurin'
    - name: run unit test
      run: mvn test

